const mg = {
    DIAMOND: "Diamond",
    GOLD: "Gold",
    SILVER: "Silver",
    BRONZE: "Bronze"
}

module.exports = [{
    metal: mg.DIAMOND,
    number: 1,
    upperBound: 1.27,
    lowerBound: 1.234,
    upperPercentile: 99,
    lowerPercentile: 95
}, {
    metal: mg.DIAMOND,
    number: 2,
    upperBound: 1.234,
    lowerBound: 1.204,
    upperPercentile: 95,
    lowerPercentile: 90
}, {
    metal: mg.DIAMOND,
    number: 3,
    upperBound: 1.204,
    lowerBound: 1.18,
    upperPercentile: 90,
    lowerPercentile: 85
}, {
    metal: mg.DIAMOND,
    number: 4,
    upperBound: 1.18,
    lowerBound: 1.159,
    upperPercentile: 85,
    lowerPercentile: 80
}, {
    metal: mg.DIAMOND,
    number: 5,
    upperBound: 1.159,
    lowerBound: 1.139,
    upperPercentile: 80,
    lowerPercentile: 75
}, {
    metal: mg.GOLD,
    number: 1,
    upperBound: 1.139,
    lowerBound: 1.118,
    upperPercentile: 75,
    lowerPercentile: 70
}, {
    metal: mg.GOLD,
    number: 2,
    upperBound: 1.118,
    lowerBound: 1.098,
    upperPercentile: 70,
    lowerPercentile: 65
}, {
    metal: mg.GOLD,
    number: 3,
    upperBound: 1.098,
    lowerBound: 1.077,
    upperPercentile: 65,
    lowerPercentile: 60
}, {
    metal: mg.GOLD,
    number: 4,
    upperBound: 1.077,
    lowerBound: 1.056,
    upperPercentile: 60,
    lowerPercentile: 55
}, {
    metal: mg.GOLD,
    number: 5,
    upperBound: 1.056,
    lowerBound: 1.036,
    upperPercentile: 55,
    lowerPercentile: 50
}, {
    metal: mg.SILVER,
    number: 1,
    upperBound: 1.036,
    lowerBound: 1.015,
    upperPercentile: 50,
    lowerPercentile: 45
}, {
    metal: mg.SILVER,
    number: 2,
    upperBound: 1.015,
    lowerBound: .99,
    upperPercentile: 45,
    lowerPercentile: 40
}, {
    metal: mg.SILVER,
    number: 3,
    upperBound: .99,
    lowerBound: .967,
    upperPercentile: 40,
    lowerPercentile: 35
}, {
    metal: mg.SILVER,
    number: 4,
    upperBound: .967,
    lowerBound: .941,
    upperPercentile: 35,
    lowerPercentile: 30
}, {
    metal: mg.SILVER,
    number: 5,
    upperBound: .941,
    lowerBound: .913,
    upperPercentile: 30,
    lowerPercentile: 25
}, {
    metal: mg.BRONZE,
    number: 1,
    upperBound: .913,
    lowerBound: .879,
    upperPercentile: 25,
    lowerPercentile: 20
}, {
    metal: mg.BRONZE,
    number: 2,
    upperBound: .879,
    lowerBound: .839,
    upperPercentile: 20,
    lowerPercentile: 15
}, {
    metal: mg.BRONZE,
    number: 3,
    upperBound: .839,
    lowerBound: .79,
    upperPercentile: 15,
    lowerPercentile: 10
}, {
    metal: mg.BRONZE,
    number: 4,
    upperBound: .79,
    lowerBound: .692,
    upperPercentile: 10,
    lowerPercentile: 5
}, {
    metal: mg.BRONZE,
    number: 5,
    upperBound: .692,
    lowerBound: .56,
    upperPercentile: 5,
    lowerPercentile: 1
}];